import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { ProjectsComponent } from './projects/projects.component';
import { ResumeComponent } from './resume/resume.component';
import { ContactComponent } from './contact/contact.component';
import { NotFoundComponent } from './not-found/not-found.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  // About folded into Home as a section. Kept as a redirect rather than
  // deleted so an old /about link lands on the site instead of the 404.
  { path: 'about', redirectTo: '/', pathMatch: 'full' },
  { path: 'projects', component: ProjectsComponent },
  {
    // Lazy — the country data and this page's markup only matter if you open the demo.
    path: 'projects/countries',
    loadComponent: () =>
      import('./projects/country-explorer/country-explorer.component').then(
        (m) => m.CountryExplorerComponent,
      ),
  },
  { path: 'resume', component: ResumeComponent },
  { path: 'contact', component: ContactComponent },

  // Throwaway design prototypes — /page1 … /page10, one theme each, for picking
  // a direction. Lazy, so none of this ships with the real site. Delete the
  // whole designs/ folder and this block once a design is chosen.
  // Spelled out rather than generated: esbuild can only follow a static import
  // path, and a template literal silently resolves to nothing at runtime.
  { path: 'page1', loadComponent: () => import('./designs/page1.component').then((m) => m.Page1Component) },
  { path: 'page2', loadComponent: () => import('./designs/page2.component').then((m) => m.Page2Component) },
  { path: 'page3', loadComponent: () => import('./designs/page3.component').then((m) => m.Page3Component) },
  { path: 'page4', loadComponent: () => import('./designs/page4.component').then((m) => m.Page4Component) },
  { path: 'page5', loadComponent: () => import('./designs/page5.component').then((m) => m.Page5Component) },
  { path: 'page6', loadComponent: () => import('./designs/page6.component').then((m) => m.Page6Component) },
  { path: 'page7', loadComponent: () => import('./designs/page7.component').then((m) => m.Page7Component) },
  { path: 'page8', loadComponent: () => import('./designs/page8.component').then((m) => m.Page8Component) },
  { path: 'page9', loadComponent: () => import('./designs/page9.component').then((m) => m.Page9Component) },
  { path: 'page10', loadComponent: () => import('./designs/page10.component').then((m) => m.Page10Component) },
  { path: 'page11', loadComponent: () => import('./designs/page11.component').then((m) => m.Page11Component) },
  { path: 'page12', loadComponent: () => import('./designs/page12.component').then((m) => m.Page12Component) },
  { path: 'page13', loadComponent: () => import('./designs/page13.component').then((m) => m.Page13Component) },
  { path: 'page14', loadComponent: () => import('./designs/page14.component').then((m) => m.Page14Component) },
  { path: 'page15', loadComponent: () => import('./designs/page15.component').then((m) => m.Page15Component) },
  { path: 'page16', loadComponent: () => import('./designs/page16.component').then((m) => m.Page16Component) },
  { path: 'page17', loadComponent: () => import('./designs/page17.component').then((m) => m.Page17Component) },
  { path: 'page18', loadComponent: () => import('./designs/page18.component').then((m) => m.Page18Component) },
  { path: 'page19', loadComponent: () => import('./designs/page19.component').then((m) => m.Page19Component) },
  { path: 'page20', loadComponent: () => import('./designs/page20.component').then((m) => m.Page20Component) },
  { path: 'page21', loadComponent: () => import('./designs/page21.component').then((m) => m.Page21Component) },
  { path: 'page22', loadComponent: () => import('./designs/page22.component').then((m) => m.Page22Component) },
  { path: 'page23', loadComponent: () => import('./designs/page23.component').then((m) => m.Page23Component) },
  { path: 'page24', loadComponent: () => import('./designs/page24.component').then((m) => m.Page24Component) },
  { path: 'page25', loadComponent: () => import('./designs/page25.component').then((m) => m.Page25Component) },
  { path: 'page26', loadComponent: () => import('./designs/page26.component').then((m) => m.Page26Component) },
  { path: 'page27', loadComponent: () => import('./designs/page27.component').then((m) => m.Page27Component) },
  { path: 'page28', loadComponent: () => import('./designs/page28.component').then((m) => m.Page28Component) },
  { path: 'page29', loadComponent: () => import('./designs/page29.component').then((m) => m.Page29Component) },
  { path: 'page30', loadComponent: () => import('./designs/page30.component').then((m) => m.Page30Component) },
  { path: 'page31', loadComponent: () => import('./designs/page31.component').then((m) => m.Page31Component) },
  { path: 'page32', loadComponent: () => import('./designs/page32.component').then((m) => m.Page32Component) },
  { path: 'page33', loadComponent: () => import('./designs/page33.component').then((m) => m.Page33Component) },
  { path: 'page34', loadComponent: () => import('./designs/page34.component').then((m) => m.Page34Component) },
  { path: 'page35', loadComponent: () => import('./designs/page35.component').then((m) => m.Page35Component) },
  { path: 'page36', loadComponent: () => import('./designs/page36.component').then((m) => m.Page36Component) },
  { path: 'page37', loadComponent: () => import('./designs/page37.component').then((m) => m.Page37Component) },
  { path: 'page38', loadComponent: () => import('./designs/page38.component').then((m) => m.Page38Component) },
  { path: 'page39', loadComponent: () => import('./designs/page39.component').then((m) => m.Page39Component) },
  { path: 'page40', loadComponent: () => import('./designs/page40.component').then((m) => m.Page40Component) },
  { path: 'page41', loadComponent: () => import('./designs/page41.component').then((m) => m.Page41Component) },
  { path: 'page42', loadComponent: () => import('./designs/page42.component').then((m) => m.Page42Component) },
  { path: 'page43', loadComponent: () => import('./designs/page43.component').then((m) => m.Page43Component) },
  { path: 'page44', loadComponent: () => import('./designs/page44.component').then((m) => m.Page44Component) },
  { path: 'page45', loadComponent: () => import('./designs/page45.component').then((m) => m.Page45Component) },
  { path: 'page46', loadComponent: () => import('./designs/page46.component').then((m) => m.Page46Component) },
  { path: 'page47', loadComponent: () => import('./designs/page47.component').then((m) => m.Page47Component) },
  { path: 'page48', loadComponent: () => import('./designs/page48.component').then((m) => m.Page48Component) },
  { path: 'page49', loadComponent: () => import('./designs/page49.component').then((m) => m.Page49Component) },
  { path: 'page50', loadComponent: () => import('./designs/page50.component').then((m) => m.Page50Component) },
  { path: 'page51', loadComponent: () => import('./designs/page51.component').then((m) => m.Page51Component) },
  { path: 'page52', loadComponent: () => import('./designs/page52.component').then((m) => m.Page52Component) },
  { path: 'page53', loadComponent: () => import('./designs/page53.component').then((m) => m.Page53Component) },
  { path: 'page54', loadComponent: () => import('./designs/page54.component').then((m) => m.Page54Component) },
  { path: 'page55', loadComponent: () => import('./designs/page55.component').then((m) => m.Page55Component) },
  { path: 'page56', loadComponent: () => import('./designs/page56.component').then((m) => m.Page56Component) },
  { path: 'page57', loadComponent: () => import('./designs/page57.component').then((m) => m.Page57Component) },
  { path: 'page58', loadComponent: () => import('./designs/page58.component').then((m) => m.Page58Component) },
  { path: 'page59', loadComponent: () => import('./designs/page59.component').then((m) => m.Page59Component) },
  { path: 'page60', loadComponent: () => import('./designs/page60.component').then((m) => m.Page60Component) },
  { path: 'page61', loadComponent: () => import('./designs/page61.component').then((m) => m.Page61Component) },
  { path: 'page62', loadComponent: () => import('./designs/page62.component').then((m) => m.Page62Component) },
  { path: 'page63', loadComponent: () => import('./designs/page63.component').then((m) => m.Page63Component) },
  { path: 'page64', loadComponent: () => import('./designs/page64.component').then((m) => m.Page64Component) },
  { path: 'page65', loadComponent: () => import('./designs/page65.component').then((m) => m.Page65Component) },
  { path: 'page66', loadComponent: () => import('./designs/page66.component').then((m) => m.Page66Component) },
  { path: 'page67', loadComponent: () => import('./designs/page67.component').then((m) => m.Page67Component) },
  { path: 'page68', loadComponent: () => import('./designs/page68.component').then((m) => m.Page68Component) },
  { path: 'page69', loadComponent: () => import('./designs/page69.component').then((m) => m.Page69Component) },
  { path: 'page70', loadComponent: () => import('./designs/page70.component').then((m) => m.Page70Component) },
  { path: 'page71', loadComponent: () => import('./designs/page71.component').then((m) => m.Page71Component) },
  { path: 'page72', loadComponent: () => import('./designs/page72.component').then((m) => m.Page72Component) },
  { path: 'page73', loadComponent: () => import('./designs/page73.component').then((m) => m.Page73Component) },
  { path: 'page74', loadComponent: () => import('./designs/page74.component').then((m) => m.Page74Component) },
  { path: 'page75', loadComponent: () => import('./designs/page75.component').then((m) => m.Page75Component) },
  { path: 'page76', loadComponent: () => import('./designs/page76.component').then((m) => m.Page76Component) },
  { path: 'page77', loadComponent: () => import('./designs/page77.component').then((m) => m.Page77Component) },
  { path: 'page78', loadComponent: () => import('./designs/page78.component').then((m) => m.Page78Component) },
  { path: 'page79', loadComponent: () => import('./designs/page79.component').then((m) => m.Page79Component) },
  { path: 'page80', loadComponent: () => import('./designs/page80.component').then((m) => m.Page80Component) },
  { path: 'page81', loadComponent: () => import('./designs/page81.component').then((m) => m.Page81Component) },
  { path: 'page82', loadComponent: () => import('./designs/page82.component').then((m) => m.Page82Component) },
  { path: 'page83', loadComponent: () => import('./designs/page83.component').then((m) => m.Page83Component) },
  { path: 'page84', loadComponent: () => import('./designs/page84.component').then((m) => m.Page84Component) },
  { path: 'page85', loadComponent: () => import('./designs/page85.component').then((m) => m.Page85Component) },
  { path: 'page86', loadComponent: () => import('./designs/page86.component').then((m) => m.Page86Component) },
  { path: 'page87', loadComponent: () => import('./designs/page87.component').then((m) => m.Page87Component) },
  { path: 'page88', loadComponent: () => import('./designs/page88.component').then((m) => m.Page88Component) },
  { path: 'page89', loadComponent: () => import('./designs/page89.component').then((m) => m.Page89Component) },
  { path: 'page90', loadComponent: () => import('./designs/page90.component').then((m) => m.Page90Component) },
  { path: 'page91', loadComponent: () => import('./designs/page91.component').then((m) => m.Page91Component) },
  { path: 'page92', loadComponent: () => import('./designs/page92.component').then((m) => m.Page92Component) },
  { path: 'page93', loadComponent: () => import('./designs/page93.component').then((m) => m.Page93Component) },
  { path: 'page94', loadComponent: () => import('./designs/page94.component').then((m) => m.Page94Component) },
  { path: 'page95', loadComponent: () => import('./designs/page95.component').then((m) => m.Page95Component) },
  { path: 'page96', loadComponent: () => import('./designs/page96.component').then((m) => m.Page96Component) },
  { path: 'page97', loadComponent: () => import('./designs/page97.component').then((m) => m.Page97Component) },
  { path: 'page98', loadComponent: () => import('./designs/page98.component').then((m) => m.Page98Component) },
  { path: 'page99', loadComponent: () => import('./designs/page99.component').then((m) => m.Page99Component) },
  { path: 'page100', loadComponent: () => import('./designs/page100.component').then((m) => m.Page100Component) },

  { path: '**', component: NotFoundComponent },
];
